---
exclude_paths:
  - .cache/ # implicit unless exclude_paths is defined in config
  - .github/

loop_var_prefix: "{role}_"

use_default_rules: true

skip_list:  # or 'skip_list' to silence them completely
  - fqcn-builtins  # Use FQCN for builtin actions.
  - yaml[new-line-at-end-of-file]

enable_list:
  - empty-string-compare # opt-in
  - no-log-password # opt-in
  - no-same-owner # opt-in.
  - yaml

offline: false

kinds:
  - yaml: "**/*.yaml-too"
