version: 0.0
os: linux
files:
  - source: .
    destination: /etc/ansible/
hooks:
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 1200
      runas: root
