---
- hosts: localhost
  become: true
  connection: local

vars_files:
{% for var_file in extra_var_files %}
  - {{ var_file }}
{% endfor                          %}

roles:
{% for role in monitored_roles %}
  - {role: {{role.name}}, tags: {{role.tag}}}
{% endfor                      %}