base_info:
  name: gitops_agent example
  owner: kaio6fellipe
  repository: ansible-devops
  branch: development

monitored_roles:
  - name: common
    tag: common
    path: /roles/common

extra_var_files:
  - name: global_dev_vars.yaml
    path: /group_vars/dev/global_dev_vars.yaml

vault_password: "{{ gitops_vault_password }}"