- name: Ping all hosts
  import_tasks: ping.yaml

- name: Allow wheel group to gain sudo without password
  import_tasks: wheel_group.yaml

- name: Allow access to users in dict
  import_tasks: admin_users.yaml
