server:
  log_level: info

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*log
      - job_name: ansible_logs
        static_configs:
          - targets: [localhost]
            labels:
              job: ansible_logs
              __path__: /etc/ansible/log/*log 
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
    clients:
      - url: http://loki-alb.{{ deploy_environment }}.private.ktech-br.com/loki/api/v1/push

# metrics:
#   wal_directory: /tmp/grafana_agent/wal
#   global:
#     scrape_interval: 15s
#     remote_write:
#     - url: http://mimir-alb.{{ deploy_environment }}.private.ktech-br.com/api/v1/push
#   configs:
#     - name: agent
#       scrape_configs:
#         - job_name: agent
#           static_configs:
#             - targets: ["127.0.0.1:12345"]
#       remote_write:
#         - url: http://mimir-alb.{{ deploy_environment }}.private.ktech-br.com/api/v1/push

integrations:
  agent:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
  # node_exporter:
  #   enabled: true
  #   rootfs_path: /host/root
  #   sysfs_path: /host/sys
  #   procfs_path: /host/proc
  # prometheus_remote_write:
  #   - url: http://mimir-alb.{{ deploy_environment }}.private.ktech-br.com/api/v1/push
