server:
  log_level: info

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*log
      - job_name: ansible_logs
        static_configs:
          - targets: [localhost]
            labels:
              job: ansible_logs
              __path__: /etc/ansible/log/*log 
    clients:
      - url: http://loki-alb.{{ deploy_environment }}.private.ktech-br.com/loki/api/v1/push
