- hosts:
    - all
  become: true
  tasks:
    - name: Create root user on hosts
      ansible.builtin.user:
        name: kaio.fellipe
        group: wheel
    - name: Make dir
      ansible.builtin.file:
        path: "/home/kaio.fellipe/.ssh"
        owner: kaio.fellipe
        group: wheel
        mode: 0700
        state: directory
    - name: Create empty file
      ansible.builtin.file:
        path: "/home/kaio.fellipe/.ssh/authorized_keys"
        owner: kaio.fellipe
        group: wheel
        mode: 0600
        state: touch
    - name: Empty authorized_keys file before copy
      ansible.builtin.shell:
        cmd: echo > /home/kaio.fellipe/.ssh/authorized_keys
        removes: /home/kaio.fellipe/.ssh/authorized_keys
        args:
          executable: /bin/bash
    - name: Copy public key
      ansible.builtin.lineinfile:
        path: "/home/kaio.fellipe/.ssh/authorized_keys"
        line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCf/eSmLtj7czYO2U4YmdNVzH\
        uG7zWoqQB0SXCQF8tlnCHvVhYiTayzVQA0cnnYdnYEd5rPfZqhqovyxuv4d0M3jC5Qvqm4\
        V99WsvQPKPu6U9YEI2NGU8xOtEPFAldHlIVYWHMAIbKqmGqL3q1dZ0J+Lql1K7/+tdr8Ds\
        0qhRji8DfIzs+qznzsb74lXzGGFljxDw2Q6BOTQSoKWX3cta3pIINAjgimAw4dVL0Ks+ad\
        zncvtukBqAdCt86917MdW1KVTAg21QI9tE8VYakSKmyETQ3IB9maC+W7+Ci8PWR6vW7HY9\
        DrtnZwNpzb4iitx2Lo8wj8pSc45uqGihUoVYf kaio.fellipe@200012-sp-nb\n"
