- name: Common playbook
  hosts: all
  become: true
  tasks:
    - name: Common role
      ansible.builtin.include_role:
        name: '../roles/common'
      
    - name: Grafana Agent role
      ansible.builtin.include_role:
        name: '../roles/grafana_agent'
