- hosts:
    - all
  become: true
  roles:
    - role: '../roles/common'
      vars:
        user: "{{ item.user }}"
        pub_rsa: "{{ item.pub_rsa }}"
      loop: "{{ admin_users | dict2items }}"
