- hosts:
    - all
  become: true
  tasks:
    - name: Common role
      loop: "{{ admin_users }}"
      ansible.builtin.include_role:
        name: '../roles/common'
      vars:
        user: "{{ item.user }}"
        pub_rsa: "{{ item.pub_rsa }}"
