name: Check Ansible directory (Development)

on:
  pull_request:
    branches: [development]
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud:
    name: Security check
    uses: kaio6fellipe/ansible-devops/.github/workflows/sonar.yml@development
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ansible-check:
    name: 'Check Ansible directory'
    needs: sonarcloud
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Install yaml Linter
      #  run: sudo apt-get install yamllint -y

      #- name: Lint yaml
      #  working-directory: .
      #  run: find . -name '*.yaml' | xargs yamllint

      # TODO: Validate why this step failed
      #- name: Run anbible-lint
      #   uses: ansible-community/ansible-lint-action@main

      - name: Install Ansible
        run: sudo apt install ansible -y

      - name: Run playbook check
        working-directory: .
        # run: ansible-playbook playbooks/*.yaml --check
        run: find playbooks/ -type f -name "*.yaml" -execdir ansible-playbook --connection=local --inventory 127.0.0.1, --limit 127.0.0.1 {} -i inventory.localhost --check \;
