name: Check Ansible directory (Development)

on:
  pull_request:
    branches: [development]
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud:
    uses: kaio6fellipe/ansible-devops/.github/workflows/sonar.yml@development
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ansible-check:
    name: 'ansible check'
    needs: sonarcloud
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Install yaml Linter
      #  run: sudo apt-get install yamllint -y

      #- name: Lint yaml
      #  working-directory: .
      #  run: find . -name '*.yaml' | xargs yamllint

      - name: Run anbible-lint
        uses: ansible-community/ansible-lint-action@main

      - name: Install Ansible
        run: sudo apt install ansible -y

      - name: Run playbook check
        working-directory: .
        run: ansible-playbook playbooks/*.yaml --check
